export const ERROR_CODES = {
  // 5XX
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // 404
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // 401
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  // 400
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  REFRESH_TOKEN_EMPTY: 'REFRESH_TOKEN_EMPTY',
};
